blueprint:
  name: Ambient Music – Play Current Selected Playlist
  domain: automation
trigger:
  - platform: state
    entity_id: binary_sensor.ambient_music_blockers_clear
    to: "on"
  - platform: state
    entity_id: select.ambient_music_playlists
    for:
      seconds: "{{ (states('number.ambient_music_volume_fade_down_seconds') | float(0)) + 1 }}"
condition:
  - condition: template
    value_template: "{{ iif(require_clear, is_state('binary_sensor.ambient_music_blockers_clear','on'), true) }}"
action:
  - service: ambient_music.play_current_playlist
mode: single
