blueprint:
  name: Ambient Music – Stop Playing
  domain: automation
trigger:
  - platform: state
    entity_id: binary_sensor.ambient_music_blockers_clear
    to: "off"
    for:
      seconds: 1
action:
  - default:
      - service: ambient_music.stop_playing
mode: single
